### PR TITLE
Change description position when rendered inline

### PR DESCRIPTION
**Pull request by attitude**
Also updates sandbox example

Closes: https://github.com/contember/private-issues/issues/97

---
This change is [Reviewable](https://reviewable.io/reviews/contember/admin/309)

### CODE REVIEW

**Comment by VojtaStanek** [comment]
🌈 Add playwright tests please 😉

**Review by attitude — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/contember/admin/309#-:-N1nNd7i6HQi-GT4oHJj:b-896fix)* status: 0 of 9 files reviewed, all discussions resolved (waiting on @VojtaStanek)

**Review by attitude — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/admin/309)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @VojtaStanek)

___
*[`packages/admin/tests/playwright/cases/fieldContainer.tsx` line 21 at r1](https://reviewable.io/reviews/contember/admin/309#-N1njBcd60ArnaS8XA57:-N1wQvil7Xfs5rn_Kv0b:b-896fix) ([raw file](https://github.com/contember/admin/blob/7e539645582a9fd03abbd8ddb00875c9486bf577/packages/admin/tests/playwright/cases/fieldContainer.tsx#L21)):*
<details><summary><i>Previously, VojtaStanek (Vojta Staněk) wrote…</i></summary><blockquote>

spaces?!
</blockquote></details>

Done.

**Review by VojtaStanek — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/admin/309)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @attitude)

**Pull request merged**
