### PR TITLE
Fix hovering toolbars

### PR DESCRIPTION
**Pull request by attitude**
Update toolbar position on resize & fix overflow clipping

Closes: https://github.com/contember/private-issues/issues/65

---
This change is [Reviewable](https://reviewable.io/reviews/contember/admin/267)

### CODE REVIEW

**Review by VojtaStanek — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/admin/267)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @attitude and @VojtaStanek)

___
*[packages/admin/src/components/bindingFacade/richText/editorSelection/useToolbarsState.ts, line 51 at r1](https://reviewable.io/reviews/contember/admin/267#-N-Y1kgy3xDEEkh5fPRE:-N-Y1kgy3xDEEkh5fPRF:bobhf7w) ([raw file](https://github.com/contember/admin/blob/fe08f7f11269b5e695b97a8b54c16c27cf50867c/packages/admin/src/components/bindingFacade/richText/editorSelection/useToolbarsState.ts#L51)):*
> ```XML
> }
> 
> // TODO use a container so that it doesn't break during resize.
> ```

Isn't this solved?
___
*[packages/admin/src/components/bindingFacade/richText/editorSelection/useToolbarsState.ts, line 73 at r1](https://reviewable.io/reviews/contember/admin/267#-N-Y2Zbj1skkXvz8PzBy:-N-Y2Zbj1skkXvz8PzBz:bxvos10) ([raw file](https://github.com/contember/admin/blob/fe08f7f11269b5e695b97a8b54c16c27cf50867c/packages/admin/src/components/bindingFacade/richText/editorSelection/useToolbarsState.ts#L73)):*
> ```XML
> 	useEffect(() => {
> 		const container = inlineToolbarRef.current
> 		let timeoutId: number
> ```

When is this assigned?
___
*[packages/admin/src/components/bindingFacade/richText/editorSelection/useToolbarsState.ts, line 82 at r1](https://reviewable.io/reviews/contember/admin/267#-N-Y3Ypp95aTTKwneGwl:-N-Y3Ypp95aTTKwneGwm:bhg2gbh) ([raw file](https://github.com/contember/admin/blob/fe08f7f11269b5e695b97a8b54c16c27cf50867c/packages/admin/src/components/bindingFacade/richText/editorSelection/useToolbarsState.ts#L82)):*
> ```XML
> 			clearTimeout(timeoutId)
> 
> 			setTimeout(() => {
> ```

Why this timeout?

**Review by VojtaStanek — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/contember/admin/267)* status: all files reviewed, 3 unresolved discussions (waiting on @attitude)

**Comment by attitude** [comment]
@VojtaStanek, timeout debounces call until resize events stop firing to skip unnecessary reflow due calls to `getBoundingClientRect()`

**Review by VojtaStanek — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/admin/267)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @attitude)

**Pull request merged**
