### PR TITLE
Pr/conditional

### PR DESCRIPTION
**Pull request by matej21**
based on #321

---
This change is [Reviewable](https://reviewable.io/reviews/contember/admin/333)

### CODE REVIEW

**Review by JanTvrdik — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/admin/333)* status: all files reviewed, 11 unresolved discussions (waiting on @matej21)

___
*[`packages/binding/src/helperComponents/helpers/FilterFieldsCollector.ts` line 38 at r1](https://reviewable.io/reviews/contember/admin/333#-N3-ycCrCtFvz6zzxlS2:-N30B1TYAW9AGzq5QP5v:b-g8c43h) ([raw file](https://github.com/contember/admin/blob/cfd28f2ce2af53ac056a0a314ca8b1f8d5d6826d/packages/binding/src/helperComponents/helpers/FilterFieldsCollector.ts#L38)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

This needs to emit friendly error message. Ideally same as `TreeNodeEnvironmentFactory.resolveField`. Maybe we can pass `Environment` instead of entity schema to allow using `TreeNodeEnvironmentFactory`?
</blockquote></details>

Also ideally we want to resolve & validate filters in static render as well, so perhaps there could be shared logic used by both FilterFieldsCollector & TreeNodeEnvironmentFactory.

**Review by matej21 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/admin/333)* status: 1 of 5 files reviewed, 11 unresolved discussions (waiting on @JanTvrdik and @matej21)

___
*[`packages/admin-sandbox/admin/pages/article.tsx` line 25 at r1](https://reviewable.io/reviews/contember/admin/333#-N3-huVR6buOWXpqc4ie:-N3JB3od4TfX2LWwhAfq:b-896fix) ([raw file](https://github.com/contember/admin/blob/cfd28f2ce2af53ac056a0a314ca8b1f8d5d6826d/packages/admin-sandbox/admin/pages/article.tsx#L25)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

both If & Collapsible must be imported from `@contember/admin`
</blockquote></details>

Done.
___
*[`packages/binding/src/helperComponents/If.tsx` line 28 at r1](https://reviewable.io/reviews/contember/admin/333#-N3-nC-u4E_NIoFdRoFm:-N3J6HKw4kss4cQJ8TkZ:b-896fix) ([raw file](https://github.com/contember/admin/blob/cfd28f2ce2af53ac056a0a314ca8b1f8d5d6826d/packages/binding/src/helperComponents/If.tsx#L28)):*
> ```XML
> 		return typeof props.condition !== 'function'
> 			? <IfFilter {...(props as IfFilterProps)} />
> 			: <IfCallback {...(props as IfCallbackProps)} />
> ```

Done.
___
*[`packages/binding/src/helperComponents/If.tsx` line 54 at r1](https://reviewable.io/reviews/contember/admin/333#-N3-o3rU9UV0iHcutWdu:-N3J6VvsD7ivVQcruEW3:b-896fix) ([raw file](https://github.com/contember/admin/blob/cfd28f2ce2af53ac056a0a314ca8b1f8d5d6826d/packages/binding/src/helperComponents/If.tsx#L54)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

useless double memo
</blockquote></details>

Done.
___
*[`packages/binding/src/helperComponents/If.tsx` line 62 at r1](https://reviewable.io/reviews/contember/admin/333#-N3-xs7k36HKje5mGZiS:-N3J6XdXAXhZ9xGZlIMt:b-896fix) ([raw file](https://github.com/contember/admin/blob/cfd28f2ce2af53ac056a0a314ca8b1f8d5d6826d/packages/binding/src/helperComponents/If.tsx#L62)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

entity schema should be passed instead of just entity name
</blockquote></details>

Done.
___
*[`packages/binding/src/helperComponents/If.tsx` line 66 at r1](https://reviewable.io/reviews/contember/admin/333#-N3-oQkg0zKUxxx5AzIT:-N3J6epF203xkD7Jx56T:b-7t8b98) ([raw file](https://github.com/contember/admin/blob/cfd28f2ce2af53ac056a0a314ca8b1f8d5d6826d/packages/binding/src/helperComponents/If.tsx#L66)):*
> ```XML
> 
> 		return <>
> 			{additionalFields}
> ```

multiline is imho more readable
___
*[`packages/binding/src/helperComponents/index.ts` line 6 at r1](https://reviewable.io/reviews/contember/admin/333#-N3-ppD9B6AqP6J4dyOa:-N3J6jWz5gqmU-J90BvO:b-896fix) ([raw file](https://github.com/contember/admin/blob/cfd28f2ce2af53ac056a0a314ca8b1f8d5d6826d/packages/binding/src/helperComponents/index.ts#L6)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

abc
</blockquote></details>

Done.
___
*[`packages/binding/src/helperComponents/helpers/FilterEvaluator.ts` line 23 at r1](https://reviewable.io/reviews/contember/admin/333#-N30-E5w3hdF3jXJ8_X5:-N3J6tCw2oiIH7fHJIPw:b-896fix) ([raw file](https://github.com/contember/admin/blob/cfd28f2ce2af53ac056a0a314ca8b1f8d5d6826d/packages/binding/src/helperComponents/helpers/FilterEvaluator.ts#L23)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

Schema.getEntity; or maybe entity.environment.getSubTreeNode().entity; possible adding getSchema shortcut to EntityAccessor
</blockquote></details>

Done.
___
*[`packages/binding/src/helperComponents/helpers/FilterFieldsCollector.ts` line 12 at r1](https://reviewable.io/reviews/contember/admin/333#-N3-puLrB7GsvpWDgEAv:-N3J6uJm49rq_c_drFlM:b-896fix) ([raw file](https://github.com/contember/admin/blob/cfd28f2ce2af53ac056a0a314ca8b1f8d5d6826d/packages/binding/src/helperComponents/helpers/FilterFieldsCollector.ts#L12)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

accept entty schema instead of entityName
</blockquote></details>

Done.
___
*[`packages/binding/src/helperComponents/helpers/FilterFieldsCollector.ts` line 18 at r1](https://reviewable.io/reviews/contember/admin/333#-N3-pyPI4D6RQixfcmN3:-N3J6v59AKyBEolq_Ow_:b-896fix) ([raw file](https://github.com/contember/admin/blob/cfd28f2ce2af53ac056a0a314ca8b1f8d5d6826d/packages/binding/src/helperComponents/helpers/FilterFieldsCollector.ts#L18)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

accept entty schema instead of entityName
</blockquote></details>

Done.
___
*[`packages/binding/src/helperComponents/helpers/FilterFieldsCollector.ts` line 38 at r1](https://reviewable.io/reviews/contember/admin/333#-N3-ycCrCtFvz6zzxlS2:-N3JAjj39QWCeb-Fe7nJ:b-2hbg23) ([raw file](https://github.com/contember/admin/blob/cfd28f2ce2af53ac056a0a314ca8b1f8d5d6826d/packages/binding/src/helperComponents/helpers/FilterFieldsCollector.ts#L38)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

Also ideally we want to resolve & validate filters in static render as well, so perhaps there could be shared logic used by both FilterFieldsCollector & TreeNodeEnvironmentFactory. 
</blockquote></details>

message improved. validation of filters in TreeNodeEnvironmentFactory is out of scope of this PR.

**Review by JanTvrdik — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/admin/333#-:-N3JG4Hh5ILfjUs0btCT:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @JanTvrdik)

**Review by JanTvrdik — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/admin/333)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matej21)

**Review by JanTvrdik — APPROVED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/admin/333)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matej21)

**Pull request merged**
