### PR TITLE
update deps (react18)

### PR DESCRIPTION
**Pull request by matej21**
This change is [Reviewable](https://reviewable.io/reviews/contember/admin/437)

### CODE REVIEW

**Review by JanTvrdik — CHANGES_REQUESTED** [review]
> Reviewed 36 of 41 files at r1, 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/admin/437)* status: all files reviewed, 3 unresolved discussions (waiting on @matej21)

___
*[`packages/admin/src/bootstrap/runReactApp.tsx` line 20 at r2](https://reviewable.io/reviews/contember/admin/437#-NHZ5JeS3KS7UUZ6j0p1:-NHZ5JeS3KS7UUZ6j0p2:bqjq71k) ([raw file](https://github.com/contember/admin/blob/99fe978fc198b2dcbdf27f6533274c0fac29487b/packages/admin/src/bootstrap/runReactApp.tsx#L20)):*
> ```XML
> 	}
> 	const errorHandler = createErrorHandler(render)
> 	errorHandler(() => render(rootEl, reactElement))
> ```

The new react 18 render supports `onRecoverableError` which should probably be connect to our error handler.
___
*[`packages/binding/src/coreComponents/DataBindingProvider.tsx` line 1 at r2](https://reviewable.io/reviews/contember/admin/437#-NHZTbzN3xP1qElZ_j1h:-NHZTbzN3xP1qElZ_j1i:b-ywuxeb) ([raw file](https://github.com/contember/admin/blob/99fe978fc198b2dcbdf27f6533274c0fac29487b/packages/binding/src/coreComponents/DataBindingProvider.tsx#L1)):*
> ```XML
> import { ComponentType, createElement, memo, ReactElement, ReactNode, StrictMode } from 'react'
> ```

unsused?
___
*[`packages/ui/package.json` line 72 at r2](https://reviewable.io/reviews/contember/admin/437#-NHZUApO9Zcv01JzW3Mk:-NHZUApP4I9sOcnkK96P:bb7r2f0) ([raw file](https://github.com/contember/admin/blob/99fe978fc198b2dcbdf27f6533274c0fac29487b/packages/ui/package.json#L72)):*
> ```JSON
> 		"react-dom": "^18",
> 		"resolve-url-loader": "4.0.0",
> 		"require-from-string": "^2.0.2",
> ```

why?

**Review by matej21 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/admin/437)* status: 40 of 50 files reviewed, 3 unresolved discussions (waiting on @JanTvrdik)

___
*[`packages/admin/src/bootstrap/runReactApp.tsx` line 20 at r2](https://reviewable.io/reviews/contember/admin/437#-NHZ5JeS3KS7UUZ6j0p1:-NHZaAdL5evr_6KHf3Sv:b-896fix) ([raw file](https://github.com/contember/admin/blob/99fe978fc198b2dcbdf27f6533274c0fac29487b/packages/admin/src/bootstrap/runReactApp.tsx#L20)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

The new react 18 render supports `onRecoverableError` which should probably be connect to our error handler.
</blockquote></details>

Done.
___
*[`packages/ui/package.json` line 72 at r2](https://reviewable.io/reviews/contember/admin/437#-NHZUApO9Zcv01JzW3Mk:-NHZVDVj8O1NWs5knLR2:b-z51vel) ([raw file](https://github.com/contember/admin/blob/99fe978fc198b2dcbdf27f6533274c0fac29487b/packages/ui/package.json#L72)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

why?
</blockquote></details>

pnpm was reporting missing peer dependency (iirc from storybook). but probably not needed -> removed
___
*[`packages/binding/src/coreComponents/DataBindingProvider.tsx` line 1 at r2](https://reviewable.io/reviews/contember/admin/437#-NHZTbzN3xP1qElZ_j1h:-NHZVilH7NGciUVV0NWc:b-896fix) ([raw file](https://github.com/contember/admin/blob/99fe978fc198b2dcbdf27f6533274c0fac29487b/packages/binding/src/coreComponents/DataBindingProvider.tsx#L1)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

unsused?
</blockquote></details>

Done.

**Review by JanTvrdik — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/admin/437)* status: all files reviewed, 1 unresolved discussion (waiting on @matej21)

___
*[`packages/admin/src/bootstrap/runReactApp.tsx` line 24 at r3](https://reviewable.io/reviews/contember/admin/437#-NH_C_hu4rGIYYLWvocG:-NH_C_hu4rGIYYLWvocH:b3m4a6l) ([raw file](https://github.com/contember/admin/blob/2eac1d750451a8fc401543aed6f89fd08d6644af/packages/admin/src/bootstrap/runReactApp.tsx#L24)):*
> ```XML
> 
> 
> export type { ReactRenderer }
> ```

why not export this from bootstrap/index.ts?

**Review by matej21 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/admin/437)* status: 49 of 51 files reviewed, 1 unresolved discussion (waiting on @JanTvrdik)

___
*[`packages/admin/src/bootstrap/runReactApp.tsx` line 24 at r3](https://reviewable.io/reviews/contember/admin/437#-NH_C_hu4rGIYYLWvocG:-NH_GZ9xD_1nLRpwonTa:b-896fix) ([raw file](https://github.com/contember/admin/blob/2eac1d750451a8fc401543aed6f89fd08d6644af/packages/admin/src/bootstrap/runReactApp.tsx#L24)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

why not export this from bootstrap/index.ts?
</blockquote></details>

Done.

**Pull request merged**
