### PR TITLE
extensible environment, add HasRole component

### PR DESCRIPTION
**Pull request by matej21**
This change is [Reviewable](https://reviewable.io/reviews/contember/admin/388)

### CODE REVIEW

**Review by VojtaStanek — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/admin/388)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @matej21 and @VojtaStanek)

___
*[`packages/binding/src/dao/Environment.ts` line 205 at r1](https://reviewable.io/reviews/contember/admin/388#-N7QtlfP3sOdOWm1yuTS:-N7QtlfP3sOdOWm1yuTT:bb7pa6j) ([raw file](https://github.com/contember/admin/blob/002a3bf162a43f09b75f2720b3b96df5811d7d4a/packages/binding/src/dao/Environment.ts#L205)):*
> ```XML
> 	}
> 
> 	public merge(other: Environment): Environment {
> ```

todo
___
*[`packages/binding/src/dao/Environment.ts` line 317 at r1](https://reviewable.io/reviews/contember/admin/388#-N7Qu7X8BIbzMkoCLILa:-N7Qu7X8BIbzMkoCLILb:bj7cmaz) ([raw file](https://github.com/contember/admin/blob/002a3bf162a43f09b75f2720b3b96df5811d7d4a/packages/binding/src/dao/Environment.ts#L317)):*
> ```XML
> 	}
> 
> 	export type ExtensionFactory<State, Result> = (state: State | undefined, environment: Environment) => Result
> ```

variables support -> addition methods on factory

**Review by VojtaStanek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/admin/388)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @matej21 and @VojtaStanek)

___
*[`packages/binding/src/dao/Environment.ts` line 251 at r1](https://reviewable.io/reviews/contember/admin/388#-N7QuuaN7-DqNNy655Wa:-N7QuuaN7-DqNNy655Wb:b-7ha2jw) ([raw file](https://github.com/contember/admin/blob/002a3bf162a43f09b75f2720b3b96df5811d7d4a/packages/binding/src/dao/Environment.ts#L251)):*
> ```XML
> 		variables: CustomVariables
> 		parent?: Environment
> 		extensions: Map<ExtensionFactory<any, any>, any>
> ```

z
o
d



_Suggestion:_
```XML
		extensions: Map<ExtensionFactory<unknown, unknown>, unknown>
```

**Review by matej21 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/admin/388)* status: all files reviewed, 5 unresolved discussions (waiting on @JanTvrdik and @VojtaStanek)

___
*[`packages/admin/src/components/Project/ProjectEnvironmentExtension.tsx` line 14 at r1](https://reviewable.io/reviews/contember/admin/388#-N7QtuwL5D5DFHXGUU-A:-N7R8pTX4Td_7dZ58Gl4:b-896fix) ([raw file](https://github.com/contember/admin/blob/002a3bf162a43f09b75f2720b3b96df5811d7d4a/packages/admin/src/components/Project/ProjectEnvironmentExtension.tsx#L14)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

replace with EnvironmentExtensionProvider which would extension and its state
</blockquote></details>

Done.
___
*[`packages/binding/src/dao/Environment.ts` line 205 at r1](https://reviewable.io/reviews/contember/admin/388#-N7QtlfP3sOdOWm1yuTS:-N7R9kNJ14_CX-skhyfB:b-896fix) ([raw file](https://github.com/contember/admin/blob/002a3bf162a43f09b75f2720b3b96df5811d7d4a/packages/binding/src/dao/Environment.ts#L205)):*
<details><summary><i>Previously, VojtaStanek (Vojta Staněk) wrote…</i></summary><blockquote>

todo
</blockquote></details>

Done.
___
*[`packages/binding/src/dao/Environment.ts` line 251 at r1](https://reviewable.io/reviews/contember/admin/388#-N7QuuaN7-DqNNy655Wa:-N7R98l4CqP-6Z1zNfy5:b-7nvlnw) ([raw file](https://github.com/contember/admin/blob/002a3bf162a43f09b75f2720b3b96df5811d7d4a/packages/binding/src/dao/Environment.ts#L251)):*
<details><summary><i>Previously, VojtaStanek (Vojta Staněk) wrote…</i></summary><blockquote>

z
o
d
</blockquote></details>

n
o
p
___
*[`packages/binding/src/dao/Environment.ts` line 317 at r1](https://reviewable.io/reviews/contember/admin/388#-N7QtJ3HAhMx3OKJrCQw:-N7R9D8Z2cKFRZpjdVoG:b-896fix) ([raw file](https://github.com/contember/admin/blob/002a3bf162a43f09b75f2720b3b96df5811d7d4a/packages/binding/src/dao/Environment.ts#L317)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

* rename to just Extension?
* wrap with object to prevent editor from appending `()` and confusing users
</blockquote></details>

Done.
___
*[`packages/binding/src/dao/Environment.ts` line 317 at r1](https://reviewable.io/reviews/contember/admin/388#-N7Qu7X8BIbzMkoCLILa:-N7R9DNe2snuEO_R2rUv:b-896fix) ([raw file](https://github.com/contember/admin/blob/002a3bf162a43f09b75f2720b3b96df5811d7d4a/packages/binding/src/dao/Environment.ts#L317)):*
<details><summary><i>Previously, VojtaStanek (Vojta Staněk) wrote…</i></summary><blockquote>

variables support -> addition methods on factory
</blockquote></details>

Done.

**Review by JanTvrdik — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/admin/388)* status: all files reviewed, 5 unresolved discussions (waiting on @matej21 and @VojtaStanek)

___
*[`packages/binding/src/accessorPropagation/EnvironmentContext.tsx` line 28 at r2](https://reviewable.io/reviews/contember/admin/388#-N7RJb465AH81EpJnRLs:-N7RJb465AH81EpJnRLt:b-gg6wxi) ([raw file](https://github.com/contember/admin/blob/ae5435442d0199f2868da9519504a186556dedba/packages/binding/src/accessorPropagation/EnvironmentContext.tsx#L28)):*
> ```XML
> 		return create(env)
> 	},
> })
> ```

make symmetric



_Suggestion:_
```XML
export const EnvironmentMiddleware = Component<EnvironmentMiddlewareProps>(
	({ children, create }) => {
		const env = useEnvironment()
		return <EnvironmentContext.Provider value={create(env)}>{children}</EnvironmentContext.Provider>
	},
	({ children, create }, env) => {
		return <EnvironmentContext.Provider value={create(env)}>{children}</EnvironmentContext.Provider>
	},
)
```
___
*[`packages/binding/src/accessorPropagation/EnvironmentContext.tsx` line 43 at r2](https://reviewable.io/reviews/contember/admin/388#-N7RHeKq-wYZfYj1hfpv:-N7RHeKq-wYZfYj1hfpw:b-gg6wxi) ([raw file](https://github.com/contember/admin/blob/ae5435442d0199f2868da9519504a186556dedba/packages/binding/src/accessorPropagation/EnvironmentContext.tsx#L43)):*
> ```XML
> 		{children}
> 	</EnvironmentMiddleware>
> )) as <S, R>(props: EnvironmentWithExtensionProps<S, R>) => ReactElement
> ```

make symmetric



_Suggestion:_
```XML
export const EnvironmentExtensionProvider: <S, R>(props: EnvironmentWithExtensionProps<S, R>) => ReactElement | null = Component(
	({ children, extension, state }) => {
		const create = useCallback((env: Environment) => env.withExtension(extension, state), [extension, state])
		return <EnvironmentMiddleware create={create}>{children}</EnvironmentMiddleware>
	},
	({ children, extension, state }) => {
		const create = (env: Environment) => env.withExtension(extension, state)
		return <EnvironmentMiddleware create={create}>{children}</EnvironmentMiddleware>
	},
)
```

**Review by matej21 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/admin/388)* status: 8 of 26 files reviewed, 5 unresolved discussions (waiting on @JanTvrdik and @VojtaStanek)

___
*[`packages/binding/src/accessorPropagation/EnvironmentContext.tsx` line 28 at r2](https://reviewable.io/reviews/contember/admin/388#-N7RJb465AH81EpJnRLs:-N7UvGUI2E5NDmxSqBb0:b8ay236) ([raw file](https://github.com/contember/admin/blob/ae5435442d0199f2868da9519504a186556dedba/packages/binding/src/accessorPropagation/EnvironmentContext.tsx#L28)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

make symmetric
</blockquote></details>

? this cannot work
___
*[`packages/binding/src/accessorPropagation/EnvironmentContext.tsx` line 43 at r2](https://reviewable.io/reviews/contember/admin/388#-N7RHeKq-wYZfYj1hfpv:-N7od1LyEuXdyGi3WD26:b-896fix) ([raw file](https://github.com/contember/admin/blob/ae5435442d0199f2868da9519504a186556dedba/packages/binding/src/accessorPropagation/EnvironmentContext.tsx#L43)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

make symmetric
</blockquote></details>

Done.

**Review by VojtaStanek — CHANGES_REQUESTED** [review]
> Reviewed 14 of 18 files at r3.
> *[Reviewable](https://reviewable.io/reviews/contember/admin/388)* status: 22 of 26 files reviewed, 4 unresolved discussions (waiting on @JanTvrdik and @matej21)

___
*[`packages/admin/src/typings/react-fix.d.ts` line 5 at r3](https://reviewable.io/reviews/contember/admin/388#-N7um5dcD-a4RrSWdBVq:-N7um5dcD-a4RrSWdBVr:boe8zjj) ([raw file](https://github.com/contember/admin/blob/1ef6dd104a139a4a5a0c565aa34ce8b2cb248ef0/packages/admin/src/typings/react-fix.d.ts#L5)):*
> ```XML
> 	export type NoConstructor<T extends Function> = T extends new (
> 		...args: unknown[]
> 	) => unknown ? never : T;
> ```

reformat



_Suggestion:_
```XML
	export type NoConstructor<T extends Function> =
        T extends new (...args: unknown[]) => unknown
            ? never
            : T
```
___
*[`packages/binding/src/dao/Environment.ts` line 251 at r1](https://reviewable.io/reviews/contember/admin/388#-N7QuuaN7-DqNNy655Wa:-N7uh_h115zv7ENMXuYr:br5mjwr) ([raw file](https://github.com/contember/admin/blob/002a3bf162a43f09b75f2720b3b96df5811d7d4a/packages/binding/src/dao/Environment.ts#L251)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

n
o
p
</blockquote></details>

s
a
d

Because: I think that the type cast should be explicit where needed.

**Review by JanTvrdik — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/admin/388)* status: 21 of 26 files reviewed, 4 unresolved discussions (waiting on @JanTvrdik, @matej21, and @VojtaStanek)

___
*[`packages/binding/src/accessorPropagation/EnvironmentContext.tsx` line 28 at r2](https://reviewable.io/reviews/contember/admin/388#-N7RJb465AH81EpJnRLs:-N8TDQHd6ih_9Slz79y6:bb7r2f0) ([raw file](https://github.com/contember/admin/blob/ae5435442d0199f2868da9519504a186556dedba/packages/binding/src/accessorPropagation/EnvironmentContext.tsx#L28)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

? this cannot work
</blockquote></details>

why?

**Review by matej21 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/admin/388)* status: 21 of 26 files reviewed, 3 unresolved discussions (waiting on @JanTvrdik and @VojtaStanek)

___
*[`packages/admin/src/typings/react-fix.d.ts` line 5 at r3](https://reviewable.io/reviews/contember/admin/388#-N7um5dcD-a4RrSWdBVq:-N8woayV0__kLtCci7ub:b-896fix) ([raw file](https://github.com/contember/admin/blob/1ef6dd104a139a4a5a0c565aa34ce8b2cb248ef0/packages/admin/src/typings/react-fix.d.ts#L5)):*
<details><summary><i>Previously, VojtaStanek (Vojta Staněk) wrote…</i></summary><blockquote>

reformat
</blockquote></details>

Done.
___
*[`packages/binding/src/accessorPropagation/EnvironmentContext.tsx` line 28 at r2](https://reviewable.io/reviews/contember/admin/388#-N7RJb465AH81EpJnRLs:-N8woc6CD9OQxIpNC9BK:b-v5zm36) ([raw file](https://github.com/contember/admin/blob/ae5435442d0199f2868da9519504a186556dedba/packages/binding/src/accessorPropagation/EnvironmentContext.tsx#L28)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

why?
</blockquote></details>

you cannot use context in static render
___
*[`packages/binding/src/dao/Environment.ts` line 251 at r1](https://reviewable.io/reviews/contember/admin/388#-N7QuuaN7-DqNNy655Wa:-N8woglr-wckIU_jnNiW:b-896fix) ([raw file](https://github.com/contember/admin/blob/002a3bf162a43f09b75f2720b3b96df5811d7d4a/packages/binding/src/dao/Environment.ts#L251)):*
<details><summary><i>Previously, VojtaStanek (Vojta Staněk) wrote…</i></summary><blockquote>

s
a
d

Because: I think that the type cast should be explicit where needed. 
</blockquote></details>

Done.

**Review by JanTvrdik — APPROVED** [review]
> Reviewed 1 of 18 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/admin/388)* status: 25 of 26 files reviewed, 2 unresolved discussions (waiting on @VojtaStanek)

**Pull request merged**
