### PR TITLE
admin server: replace relative paths in index.html

### PR DESCRIPTION
**Pull request by matej21**
This change is [Reviewable](https://reviewable.io/reviews/contember/admin/277)

### CODE REVIEW

**Review by VojtaStanek — APPROVED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/admin/277)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matej21)

**Review by JanTvrdik — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/admin/277)* status: all files reviewed, 1 unresolved discussion (waiting on @matej21)

___
*[ee/admin-server/src/controllers/ProjectController.ts, line 63 at r2](https://reviewable.io/reviews/contember/admin/277#-N07AJEr35MN2hMNa-O8:-N07AJEr35MN2hMNa-O9:b436pqr) ([raw file](https://github.com/contember/admin/blob/b3630571cd026baf04782bb43728724144b53971/ee/admin-server/src/controllers/ProjectController.ts#L63)):*
> ```XML
> 	private preprocessIndexHtml(html: string, params: ProjectParams): string {
> 		return html.replaceAll(/(src|href)="\.\/assets\//g, ((substring, attrName) => {
> 			return `${attrName}="/${params.projectSlug}/assets/`
> ```

the assets directory may have different name



_Suggestion:_
```XML
	private preprocessIndexHtml(html: string, params: ProjectParams): string {
		return html.replaceAll(/(src|href)="\.\//g, ((substring, attrName) => {
			return `${attrName}="/${params.projectSlug}/`
		}))
	}
```

**Review by JanTvrdik — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/contember/admin/277)* status: all files reviewed, 3 unresolved discussions (waiting on @matej21)

___
*[packages/admin/src/components/ApplicationEntrypoint.tsx, line 39 at r2](https://reviewable.io/reviews/contember/admin/277#-N07C_H34Bn3qeSUNFzI:-N07C_H34Bn3qeSUNFzJ:undefined) ([raw file](https://github.com/contember/admin/blob/b3630571cd026baf04782bb43728724144b53971/packages/admin/src/components/ApplicationEntrypoint.tsx#L39)):*
> ```XML
> 	if (basePath === './') {
> 		basePath = `/${projectName}/`
> 	}
> ```





_Suggestion:_
```XML
	const projectSlug = props.project === '__PROJECT_SLUG__'
		? window.location.pathname.split('/')[1]
		: props.project

	const basePath = props.basePath === './'
		? `/${projectName}/`
		: (props.basePath ?? '/')
```
___
*[packages/admin/src/components/ApplicationEntrypoint.tsx, line 64 at r2](https://reviewable.io/reviews/contember/admin/277#-N07CwTS0Cfqct8IBEnk:-N07CwTS0Cfqct8IBEnl:undefined) ([raw file](https://github.com/contember/admin/blob/b3630571cd026baf04782bb43728724144b53971/packages/admin/src/components/ApplicationEntrypoint.tsx#L64)):*
> ```XML
> 										sessionToken={props.sessionToken}
> 										loginToken={props.loginToken}
> 										project={projectName}
> ```





_Suggestion:_
```XML
project={projectSlug}
```

**Review by JanTvrdik — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/admin/277)* status: all files reviewed, 3 unresolved discussions (waiting on @matej21)

___
*[packages/admin/src/components/ApplicationEntrypoint.tsx, line 39 at r2](https://reviewable.io/reviews/contember/admin/277#-N07C_H34Bn3qeSUNFzI:-N07DDfF61P0AlWGiMuI:b-l1mbx9) ([raw file](https://github.com/contember/admin/blob/b3630571cd026baf04782bb43728724144b53971/packages/admin/src/components/ApplicationEntrypoint.tsx#L39)):*
> ```XML
> 	if (basePath === './') {
> 		basePath = `/${projectName}/`
> 	}
> ```

or maybe just `__PROJECT__`

**Review by matej21 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/admin/277)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @JanTvrdik and @VojtaStanek)

___
*[ee/admin-server/src/controllers/ProjectController.ts, line 63 at r2](https://reviewable.io/reviews/contember/admin/277#-N07AJEr35MN2hMNa-O8:-N0GFuMn78A-3g4fzqFU:b-896fix) ([raw file](https://github.com/contember/admin/blob/b3630571cd026baf04782bb43728724144b53971/ee/admin-server/src/controllers/ProjectController.ts#L63)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

the assets directory may have different name
</blockquote></details>

Done.
___
*[packages/admin/src/components/ApplicationEntrypoint.tsx, line 39 at r2](https://reviewable.io/reviews/contember/admin/277#-N07C_H34Bn3qeSUNFzI:-N0GFtIk8my734U4E8so:b-896fix) ([raw file](https://github.com/contember/admin/blob/b3630571cd026baf04782bb43728724144b53971/packages/admin/src/components/ApplicationEntrypoint.tsx#L39)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

or maybe just `__PROJECT__`
</blockquote></details>

Done.
___
*[packages/admin/src/components/ApplicationEntrypoint.tsx, line 64 at r2](https://reviewable.io/reviews/contember/admin/277#-N07CwTS0Cfqct8IBEnk:-N0GFtexBQASUyo3PH-6:b-896fix) ([raw file](https://github.com/contember/admin/blob/b3630571cd026baf04782bb43728724144b53971/packages/admin/src/components/ApplicationEntrypoint.tsx#L64)):*
> ```XML
> 										sessionToken={props.sessionToken}
> 										loginToken={props.loginToken}
> 										project={projectName}
> ```

Done.

**Review by VojtaStanek — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/admin/277)* status: all files reviewed, 3 unresolved discussions (waiting on @JanTvrdik)

**Review by JanTvrdik — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/admin/277#-:-N0GP-av8RGAZRWE8IpU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matej21)

**Pull request merged**
