### PR TITLE
Pr/data grid header

### PR DESCRIPTION
**Pull request by attitude**
Closes https://github.com/contember/private-issues/issues/94

---
This change is [Reviewable](https://reviewable.io/reviews/contember/admin/268)

### CODE REVIEW

**Review by VojtaStanek — CHANGES_REQUESTED** [review]
> Reviewed 11 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/admin/268)* status: 11 of 20 files reviewed, 1 unresolved discussion (waiting on @attitude and @VojtaStanek)

___
*[packages/ui/src/components/Layout/LayoutPageContent.tsx, line 6 at r1](https://reviewable.io/reviews/contember/admin/268#-N014Cjl6-Kzo1XB5eDd:-N014Cjl6-Kzo1XB5eDe:b-rb9b0p) ([raw file](https://github.com/contember/admin/blob/46562a5bf7eae62f27b60b8439c9326bc8d9c3aa/packages/ui/src/components/Layout/LayoutPageContent.tsx#L6)):*
> ```XML
> 
> export const LayoutPageContent = memo(({ children }: NativeProps<HTMLDivElement>) => {
>   const componentClassName = useComponentClassName('layout-page-content')
> ```

are you using space ident here?

**Review by VojtaStanek — CHANGES_REQUESTED** [review]
> Reviewed 8 of 20 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/admin/268)* status: all files reviewed, 2 unresolved discussions (waiting on @attitude)

___
*[packages/ui/src/components/Layout/LayoutPageStickyContainer.tsx, line 28 at r2](https://reviewable.io/reviews/contember/admin/268#-N0AIPNy2fwnkFrV0ify:-N0AIPNy2fwnkFrV0ifz:b-8bwjvj) ([raw file](https://github.com/contember/admin/blob/7fb2fdff60a0049ae9a67818a212cd7e79639929/packages/ui/src/components/Layout/LayoutPageStickyContainer.tsx#L28)):*
> ```XML
> 		'--cui-sticky-container-offset-right': right,
> 		'bottom': bottom === 0 ? 0 : bottom,
> 		'top': top === 0 ? 0 : top,
> ```

why the ternary operators?
___
*[packages/ui/src/components/Stack/Stack.tsx, line 52 at r2](https://reviewable.io/reviews/contember/admin/268#-N0AK1W96qnS5L_qSf_6:-N0AK1W96qnS5L_qSf_7:b-enkhbx) ([raw file](https://github.com/contember/admin/blob/7fb2fdff60a0049ae9a67818a212cd7e79639929/packages/ui/src/components/Stack/Stack.tsx#L52)):*
> ```XML
> 			const style: CSSProperties = useMemo(() => ({
> 				...(typeof basis !== 'boolean' ? { flexBasis: basis } : {}),
> 				...(typeof grow !== 'boolean' ? { flexGrow: grow } : {}),
> ```

why the boolean?

**Comment by attitude** [comment]
> why the ternary operators?
Condition changed. Fogot to simplyfy. Will change.

> why the boolean
Shorthand, in most cases `flexGrow={1}` is necessary `flexGrow` (`true`) could/should works the same.

**Review by VojtaStanek — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/admin/268)* status: all files reviewed, 1 unresolved discussion (waiting on @attitude)

**Review by VojtaStanek — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/admin/268)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @attitude)

**Pull request merged**
