### PR TITLE
Fix console warnings

### PR DESCRIPTION
**Pull request by attitude**
This change is [Reviewable](https://reviewable.io/reviews/contember/admin/380)

### CODE REVIEW

**Review by matej21 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/admin/380)* status: all files reviewed, 1 unresolved discussion (waiting on @attitude)

___
*[`package.json` line 59 at r2](https://reviewable.io/reviews/contember/admin/380#-N7GqboA0EWjjXc8YUF_:-N7GqboB669NO7hkMwRJ:brwi7y2) ([raw file](https://github.com/contember/admin/blob/1a969bef9885f524635fd1d2afddf93391c72d1c/package.json#L59)):*
> ```JSON
> 		"vitest": "0.6.1"
> 	}
> }
> ```

missing newline at EOF

**Review by attitude — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/admin/380)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @matej21)

___
*[`package.json` line 59 at r2](https://reviewable.io/reviews/contember/admin/380#-N7GqboA0EWjjXc8YUF_:-N7GrkIZ-1CVoBIpk3rT:b-896fix) ([raw file](https://github.com/contember/admin/blob/1a969bef9885f524635fd1d2afddf93391c72d1c/package.json#L59)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

missing newline at EOF
</blockquote></details>

Done.

**Review by matej21 — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/admin/380)* status: all files reviewed, 1 unresolved discussion (waiting on @matej21)

**Review by matej21 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/admin/380)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @attitude)

**Pull request merged**
