### PR TITLE
select or create

### PR DESCRIPTION
**Pull request by matej21**
This change is [Reviewable](https://reviewable.io/reviews/contember/admin/290)

### CODE REVIEW

**Comment by attitude** [comment]
@JanTvrdik or @VojtaStane, is it possible to review and merge this PR anytime soon? I am blocked and I think I could use some pieces for media select picker.

**Review by JanTvrdik — CHANGES_REQUESTED** [review]
> Reviewed 39 of 71 files at r1, 2 of 43 files at r2, 3 of 46 files at r3, 42 of 43 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/admin/290)* status: all files reviewed, 6 unresolved discussions (waiting on @matej21)

___
*[`packages/admin/src/components/bindingFacade/fields/ChoiceField/renderDynamicChoiceFieldStatic.tsx` line 11 at r2](https://reviewable.io/reviews/contember/admin/290#-N2BsPpB3EiTU68zOLES:-N2BsPpB3EiTU68zOLET:b-k8c4tb) ([raw file](https://github.com/contember/admin/blob/157d031ca4493c1afb1dcba7cfa554b2e0e970ff/packages/admin/src/components/bindingFacade/fields/ChoiceField/renderDynamicChoiceFieldStatic.tsx#L11)):*
> ```XML
> } from '@contember/binding'
> import { BaseDynamicChoiceField } from './BaseDynamicChoiceField'
> import { NIL_UUID } from '@contember/binding'
> ```

merge imports
___
*[`packages/admin/src/components/bindingFacade/fields/ChoiceField/useOnAddNew.tsx` line 17 at r5](https://reviewable.io/reviews/contember/admin/290#-N2zLxt2-Xca3FV6JDLt:-N2zLxt2-Xca3FV6JDLu:b45h) ([raw file](https://github.com/contember/admin/blob/de1c39387cb6a3552a0a6b5982fdb80d63bd358f/packages/admin/src/components/bindingFacade/fields/ChoiceField/useOnAddNew.tsx#L17)):*
> ```XML
> export const useOnAddNew = ({ createNewForm, connect, ...props }: BaseDynamicChoiceField & { connect: (entity: EntityAccessor) => void }) => {
> 	const desugaredOptionPath = useDesugaredOptionPath(props)
> 	const getSubtree = useGetEntityListSubTree()
> ```





_Suggestion:_
```XML
const getSubTree = useGetEntityListSubTree()
```
___
*[`packages/admin/src/components/bindingFacade/fields/ChoiceField/useOnAddNew.tsx` line 27 at r5](https://reviewable.io/reviews/contember/admin/290#-N2zOyLa8y2Qq5qDU_jt:-N2zOyLa8y2Qq5qDU_ju:undefined) ([raw file](https://github.com/contember/admin/blob/de1c39387cb6a3552a0a6b5982fdb80d63bd358f/packages/admin/src/components/bindingFacade/fields/ChoiceField/useOnAddNew.tsx#L27)):*
> ```XML
> 			}
> 			return async () => {
> 				const subtree = getSubtree({
> ```





_Suggestion:_
```XML
const subTree
```
___
*[`packages/admin/src/components/bindingFacade/fields/ChoiceField/useOnAddNew.tsx` line 39 at r5](https://reviewable.io/reviews/contember/admin/290#-N2zLLAAB9iaqc8JCwfu:-N2zLLAAB9iaqc8JCwfv:undefined) ([raw file](https://github.com/contember/admin/blob/de1c39387cb6a3552a0a6b5982fdb80d63bd358f/packages/admin/src/components/bindingFacade/fields/ChoiceField/useOnAddNew.tsx#L39)):*
> ```XML
> 					heading: localization('choiceField.createNew.dialogTitle'),
> 					content: contentProps => (
> 						<Stack direction={'vertical'}>
> ```





_Suggestion:_
```XML
<Stack direction="vertical">
```
___
*[`packages/admin-sandbox/admin/pages/article.tsx` line 74 at r5](https://reviewable.io/reviews/contember/admin/290#-N3-ORCD6EKqz7hYqaKa:-N3-ORCD6EKqz7hYqaKb:undefined) ([raw file](https://github.com/contember/admin/blob/de1c39387cb6a3552a0a6b5982fdb80d63bd358f/packages/admin-sandbox/admin/pages/article.tsx#L74)):*
> ```XML
> 			fields: 'Tag.name',
> 			orderBy: 'name desc',
> 		}} createNewForm={<TextField field={'name'} label={'Name'} />}/>
> ```





_Suggestion:_
```XML
		<MultiSelectField
			label="tags"
			field="tags"
			options={{ fields: 'Tag.name', orderBy: 'name desc' }}
			createNewForm={<TextField field="name" label="Name" />}
		/>
```
___
*[`packages/binding/src/core/MutationGenerator.ts` line 35 at r5](https://reviewable.io/reviews/contember/admin/290#-N3-RUdU2rKN1IwKvY8y:-N3-RUdU2rKN1IwKvY8z:bel5wvb) ([raw file](https://github.com/contember/admin/blob/de1c39387cb6a3552a0a6b5982fdb80d63bd358f/packages/binding/src/core/MutationGenerator.ts#L35)):*
> ```XML
> 			const processedPlaceholdersByEntity: ProcessedPlaceholdersByEntity = new Map()
> 
> 			const states = Array.from(this.treeStore.subTreeStatesByRoot.entries())
> ```

reformat; use for loops & ifs instead of Array.from + flatMap + map + filter

**Review by matej21 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/admin/290)* status: 50 of 89 files reviewed, 6 unresolved discussions (waiting on @JanTvrdik)

___
*[`packages/admin/src/components/bindingFacade/fields/ChoiceField/renderDynamicChoiceFieldStatic.tsx` line 11 at r2](https://reviewable.io/reviews/contember/admin/290#-N2BsPpB3EiTU68zOLES:-N3-j-TL5s3C_MW9Z0-U:b-896fix) ([raw file](https://github.com/contember/admin/blob/157d031ca4493c1afb1dcba7cfa554b2e0e970ff/packages/admin/src/components/bindingFacade/fields/ChoiceField/renderDynamicChoiceFieldStatic.tsx#L11)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

merge imports
</blockquote></details>

Done.
___
*[`packages/admin/src/components/bindingFacade/fields/ChoiceField/useOnAddNew.tsx` line 17 at r5](https://reviewable.io/reviews/contember/admin/290#-N2zLxt2-Xca3FV6JDLt:-N3-j5lF9IdgI2n5Gz4d:b-896fix) ([raw file](https://github.com/contember/admin/blob/de1c39387cb6a3552a0a6b5982fdb80d63bd358f/packages/admin/src/components/bindingFacade/fields/ChoiceField/useOnAddNew.tsx#L17)):*
> ```XML
> export const useOnAddNew = ({ createNewForm, connect, ...props }: BaseDynamicChoiceField & { connect: (entity: EntityAccessor) => void }) => {
> 	const desugaredOptionPath = useDesugaredOptionPath(props)
> 	const getSubtree = useGetEntityListSubTree()
> ```

Done.
___
*[`packages/admin/src/components/bindingFacade/fields/ChoiceField/useOnAddNew.tsx` line 27 at r5](https://reviewable.io/reviews/contember/admin/290#-N2zOyLa8y2Qq5qDU_jt:-N3-jD8S3zIM8O-fqRvF:b-896fix) ([raw file](https://github.com/contember/admin/blob/de1c39387cb6a3552a0a6b5982fdb80d63bd358f/packages/admin/src/components/bindingFacade/fields/ChoiceField/useOnAddNew.tsx#L27)):*
> ```XML
> 			}
> 			return async () => {
> 				const subtree = getSubtree({
> ```

Done.
___
*[`packages/admin/src/components/bindingFacade/fields/ChoiceField/useOnAddNew.tsx` line 39 at r5](https://reviewable.io/reviews/contember/admin/290#-N2zLLAAB9iaqc8JCwfu:-N3-jOMOEZePoay4EoZK:b-896fix) ([raw file](https://github.com/contember/admin/blob/de1c39387cb6a3552a0a6b5982fdb80d63bd358f/packages/admin/src/components/bindingFacade/fields/ChoiceField/useOnAddNew.tsx#L39)):*
> ```XML
> 					heading: localization('choiceField.createNew.dialogTitle'),
> 					content: contentProps => (
> 						<Stack direction={'vertical'}>
> ```

Done.
___
*[`packages/admin-sandbox/admin/pages/article.tsx` line 74 at r5](https://reviewable.io/reviews/contember/admin/290#-N3-ORCD6EKqz7hYqaKa:-N3-jia5B51KZ8YuiOI5:b-896fix) ([raw file](https://github.com/contember/admin/blob/de1c39387cb6a3552a0a6b5982fdb80d63bd358f/packages/admin-sandbox/admin/pages/article.tsx#L74)):*
> ```XML
> 			fields: 'Tag.name',
> 			orderBy: 'name desc',
> 		}} createNewForm={<TextField field={'name'} label={'Name'} />}/>
> ```

Done.
___
*[`packages/binding/src/core/MutationGenerator.ts` line 35 at r5](https://reviewable.io/reviews/contember/admin/290#-N3-RUdU2rKN1IwKvY8y:-N3-ochA99MbGGtVomJw:b-896fix) ([raw file](https://github.com/contember/admin/blob/de1c39387cb6a3552a0a6b5982fdb80d63bd358f/packages/binding/src/core/MutationGenerator.ts#L35)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

reformat; use for loops & ifs instead of Array.from + flatMap + map + filter
</blockquote></details>

Done.

**Review by JanTvrdik — APPROVED** [review]
> Reviewed 39 of 39 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/admin/290)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matej21)

**Review by JanTvrdik — APPROVED** [review]
> Reviewed 7 of 16 files at r7, 20 of 31 files at r8, 4 of 5 files at r9, 12 of 18 files at r10, 6 of 6 files at r11, 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/admin/290)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matej21)

**Pull request merged**
