### PR TITLE
AutoGrid

### PR DESCRIPTION
**Pull request by JanTvrdik**
Implements automatic datagrid for entities as a lightweight and secure Adminer alternative.

- - -
This change is [Reviewable](https://reviewable.io/reviews/contember/admin/397)

### CODE REVIEW

**Review by matej21 — CHANGES_REQUESTED** [review]
> Reviewed 36 of 36 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/admin/397)* status: all files reviewed, 19 unresolved discussions (waiting on @JanTvrdik)

___
*[`ee/admin-server/public/_panel/components/StudioNavigation.tsx` line 8 at r1](https://reviewable.io/reviews/contember/admin/397#-N9WBp73EdQeE8bGeA_G:-N9WBp73EdQeE8bGeA_H:b-zhmrop) ([raw file](https://github.com/contember/admin/blob/7ced8bcddae1aa8aa6f5049dcf4790594728f961/ee/admin-server/public/_panel/components/StudioNavigation.tsx#L8)):*
> ```XML
> 	const env = useEnvironment()
> 	const schema = env.getSchema()
> 	const entities = Array.from(schema.store.entities.values()).map(it => it.name).sort()
> ```

i don't like the "store" property access. maybe introduce getEntities on schema?
___
*[`ee/admin-server/public/_panel/pages/studioGrid.tsx` line 31 at r1](https://reviewable.io/reviews/contember/admin/397#-N9WA_a5Dkz5NQOY4O-C:-N9WA_a5Dkz5NQOY4O-D:b-5hltyh) ([raw file](https://github.com/contember/admin/blob/7ced8bcddae1aa8aa6f5049dcf4790594728f961/ee/admin-server/public/_panel/pages/studioGrid.tsx#L31)):*
> ```XML
> 		<DataBindingProvider stateComponent={FeedbackRenderer}>
> 			<LayoutRenderer title={`List ${entity}`} actions={actions} pageContentLayout="start">
> 				<AutoGrid entities={entity + filter} createViewLinkTarget={createViewLinkTarget} createEditLinkTarget={createEditLinkTarget} />
> ```

```
				{
					entityName: entity,
					filter: request.parameters.id ? {
						id: { eq: request.parameters.id },
					} : {},
				}
```

___
*[`packages/admin/src/components/Auto/AutoCell.tsx` line 24 at r1](https://reviewable.io/reviews/contember/admin/397#-N9WETvZ9ZenH0NooUeT:-N9WETvZ9ZenH0NooUeU:bucv1g5) ([raw file](https://github.com/contember/admin/blob/7ced8bcddae1aa8aa6f5049dcf4790594728f961/packages/admin/src/components/Auto/AutoCell.tsx#L24)):*
> ```XML
> import { AutoLabel } from './AutoLabel'
> 
> const ClickToEdit = Component<{ view: ReactNode, edit: ReactNode }>(
> ```

this is an utility component, should not be first in this file.
___
*[`packages/admin/src/components/Auto/AutoCell.tsx` line 34 at r1](https://reviewable.io/reviews/contember/admin/397#-N9WCPQN6AHwHGizvu-C:-N9WCPQN6AHwHGizvu-D:undefined) ([raw file](https://github.com/contember/admin/blob/7ced8bcddae1aa8aa6f5049dcf4790594728f961/packages/admin/src/components/Auto/AutoCell.tsx#L34)):*
> ```XML
> 	},
> 	props => {
> 		return <>{props.edit}{props.view}</>
> ```





_Suggestion:_
```XML
<>
	{props.edit}
	{props.view}
</>
```
___
*[`packages/admin/src/components/Auto/AutoCell.tsx` line 50 at r1](https://reviewable.io/reviews/contember/admin/397#-N9WD2Ds-ZrcnjHnZl-p:-N9WD2Ds-ZrcnjHnZl-q:bgqw92o) ([raw file](https://github.com/contember/admin/blob/7ced8bcddae1aa8aa6f5049dcf4790594728f961/packages/admin/src/components/Auto/AutoCell.tsx#L50)):*
> ```XML
> 
> 		if (field.__typename === '_Column') {
> 			if (field.name === 'id') {
> ```

=== PRIMARY_KEY_NAME
___
*[`packages/admin/src/components/Auto/AutoCell.tsx` line 97 at r1](https://reviewable.io/reviews/contember/admin/397#-N9WDj4DBBjHsNqqs1Gf:-N9WDj4DBBjHsNqqs1Gg:bshbiz8) ([raw file](https://github.com/contember/admin/blob/7ced8bcddae1aa8aa6f5049dcf4790594728f961/packages/admin/src/components/Auto/AutoCell.tsx#L97)):*
> ```XML
> 						format={it => (
> 							<ClickToEdit
> 								view={it ? '✓' : '✗'}
> ```

unify with characters in BooleanFieldView
___
*[`packages/admin/src/components/Auto/AutoCell.tsx` line 105 at r1](https://reviewable.io/reviews/contember/admin/397#-N9WDYNmAzuNovNsI_Yp:-N9WDYNmAzuNovNsI_Yq:bheduq6) ([raw file](https://github.com/contember/admin/blob/7ced8bcddae1aa8aa6f5049dcf4790594728f961/packages/admin/src/components/Auto/AutoCell.tsx#L105)):*
> ```XML
> 
> 			} else if (field.type === 'Enum') {
> 				const enumValues = Array.from(schema.store.enums.get(field.enumName!)!)
> ```

add getEnum method
___
*[`packages/admin/src/components/Auto/AutoCell.tsx` line 163 at r1](https://reviewable.io/reviews/contember/admin/397#-N9WHHhZ6KZdU5x-yha7:-N9WHHhZ6KZdU5x-yha8:bcnejtv) ([raw file](https://github.com/contember/admin/blob/7ced8bcddae1aa8aa6f5049dcf4790594728f961/packages/admin/src/components/Auto/AutoCell.tsx#L163)):*
> ```XML
> 				)
> 
> 			} else {
> ```

Json is missing
___
*[`packages/admin/src/components/Auto/AutoCell.tsx` line 164 at r1](https://reviewable.io/reviews/contember/admin/397#-N9WCgps7_NdidNXB72c:-N9WCgps7_NdidNXB72d:btlf2xh) ([raw file](https://github.com/contember/admin/blob/7ced8bcddae1aa8aa6f5049dcf4790594728f961/packages/admin/src/components/Auto/AutoCell.tsx#L164)):*
> ```XML
> 
> 			} else {
> 				return <></>
> ```

throw an error or render some warning node.
___
*[`packages/admin/src/components/Auto/AutoField.tsx` line 56 at r1](https://reviewable.io/reviews/contember/admin/397#-N9WH8IMBl75dZMv--ir:-N9WH8IMBl75dZMv--is:b78d822) ([raw file](https://github.com/contember/admin/blob/7ced8bcddae1aa8aa6f5049dcf4790594728f961/packages/admin/src/components/Auto/AutoField.tsx#L56)):*
> ```XML
> 				return <SelectField {...common} options={options} allowNull={field.nullable} />
> 
> 			} else {
> ```

Json is missing (also missing in SchemaKnownColumnType)
___
*[`packages/admin/src/components/Auto/AutoField.tsx` line 57 at r1](https://reviewable.io/reviews/contember/admin/397#-N9WENt28sL8Kr3uGH4P:-N9WENt28sL8Kr3uGH4Q:bk83na9) ([raw file](https://github.com/contember/admin/blob/7ced8bcddae1aa8aa6f5049dcf4790594728f961/packages/admin/src/components/Auto/AutoField.tsx#L57)):*
> ```XML
> 
> 			} else {
> 				return null
> ```

throw error / show warning
___
*[`packages/admin/src/components/Auto/AutoFields.tsx` line 32 at r1](https://reviewable.io/reviews/contember/admin/397#-N9WFTi57lYsyD-2Pe5M:-N9WFTi57lYsyD-2Pe5N:bxq0fv3) ([raw file](https://github.com/contember/admin/blob/7ced8bcddae1aa8aa6f5049dcf4790594728f961/packages/admin/src/components/Auto/AutoFields.tsx#L32)):*
> ```XML
> 		))
> 
> 		return <>{autoFields}</>
> ```

static and dynamic render are same except getting the env => extract to renderAutoFields
___
*[`packages/admin/src/components/Auto/AutoGrid.tsx` line 6 at r1](https://reviewable.io/reviews/contember/admin/397#-N9WGJjB5eLiW_YeXgNu:-N9WGJjB5eLiW_YeXgNv:bsce4cp) ([raw file](https://github.com/contember/admin/blob/7ced8bcddae1aa8aa6f5049dcf4790594728f961/packages/admin/src/components/Auto/AutoGrid.tsx#L6)):*
> ```XML
> import { AutoCell } from './AutoCell'
> 
> const createDataGridColumns = (
> ```

move this helper function to end of file
___
*[`packages/admin/src/components/Auto/AutoGrid.tsx` line 14 at r1](https://reviewable.io/reviews/contember/admin/397#-N9WG58z0snoQ3TLa1yy:-N9WG58z0snoQ3TLa1yz:b-sra1ol) ([raw file](https://github.com/contember/admin/blob/7ced8bcddae1aa8aa6f5049dcf4790594728f961/packages/admin/src/components/Auto/AutoGrid.tsx#L14)):*
> ```XML
> 	const entitySchema = schema.getEntity(entityName)!
> 
> 	const fieldColumns = Array.from(entitySchema.fields.values()).map(it => (
> ```

you can use second argument of Array.from to map values immediatelly
___
*[`packages/admin/src/components/Auto/AutoGrid.tsx` line 54 at r1](https://reviewable.io/reviews/contember/admin/397#-N9WFrPCA8GfjmOe7R-K:-N9WFrPCA8GfjmOe7R-L:bqsizj0) ([raw file](https://github.com/contember/admin/blob/7ced8bcddae1aa8aa6f5049dcf4790594728f961/packages/admin/src/components/Auto/AutoGrid.tsx#L54)):*
> ```XML
> 		const { createViewLinkTarget, createEditLinkTarget, ...dataGridProps } = props
> 
> 		return <DataGrid {...dataGridProps} children={createDataGridColumns(schema, entities.entityName, createViewLinkTarget, createEditLinkTarget)} />
> ```

static and dynamic render are same except getting the env => extract to renderAutoGrid
___
*[`packages/admin/src/components/Auto/AutoLabel.tsx` line 24 at r1](https://reviewable.io/reviews/contember/admin/397#-N9WGPsb7qhbPb9JPV1-:-N9WGPsb7qhbPb9JPV10:b-lqk38i) ([raw file](https://github.com/contember/admin/blob/7ced8bcddae1aa8aa6f5049dcf4790594728f961/packages/admin/src/components/Auto/AutoLabel.tsx#L24)):*
> ```XML
> 
> 		const optionLabel = <Field field={field} format={it => formatString(humanFieldSchema.type, it)} />
> 		return createLink ? <Link to={createLink(entity.name)}>{optionLabel}</Link> : optionLabel
> ```

static and dynamic render are same except getting the env => extract to renderAutoLabel
___
*[`packages/admin/src/components/Auto/utils.tsx` line 4 at r1](https://reviewable.io/reviews/contember/admin/397#-N9WGUdq8h1hv5vD-Hxk:-N9WGUdq8h1hv5vD-Hxl:b-1fl2nj) ([raw file](https://github.com/contember/admin/blob/7ced8bcddae1aa8aa6f5049dcf4790594728f961/packages/admin/src/components/Auto/utils.tsx#L4)):*
> ```XML
> 
> export const getHumanFriendlyField = (entitySchema: SchemaEntity) => {
> 	for (const field of ['name', 'title', 'heading', 'label', 'code', 'slug']) {
> ```

caption, description

also, imho slug > code
___
*[`packages/admin/src/components/Auto/utils.tsx` line 10 at r1](https://reviewable.io/reviews/contember/admin/397#-N9WGpkWBlJKJE0C4aAf:-N9WGpkWBlJKJE0C4aAg:b-c1gz3n) ([raw file](https://github.com/contember/admin/blob/7ced8bcddae1aa8aa6f5049dcf4790594728f961/packages/admin/src/components/Auto/utils.tsx#L10)):*
> ```XML
> 	}
> 
> 	return 'id'
> ```

PRIMARY_KEY_NAME
___
*[`packages/admin/src/components/Auto/utils.tsx` line 22 at r1](https://reviewable.io/reviews/contember/admin/397#-N9WGw_HCPBEEYrlmOQ1:-N9WGw_HCPBEEYrlmOQ2:bkcg9bl) ([raw file](https://github.com/contember/admin/blob/7ced8bcddae1aa8aa6f5049dcf4790594728f961/packages/admin/src/components/Auto/utils.tsx#L22)):*
> ```XML
> 
> 	} else if (type === 'String') {
> 		return value.length > 100 ? value.slice(0, 100) + '...' : value
> ```

full value to title?

**Review by JanTvrdik — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/admin/397)* status: 24 of 48 files reviewed, 19 unresolved discussions (waiting on @JanTvrdik and @matej21)

___
*[`ee/admin-server/public/_panel/components/StudioNavigation.tsx` line 8 at r1](https://reviewable.io/reviews/contember/admin/397#-N9WBp73EdQeE8bGeA_G:-N9WlmfTDk3MlQsHHmzb:b-896fix) ([raw file](https://github.com/contember/admin/blob/7ced8bcddae1aa8aa6f5049dcf4790594728f961/ee/admin-server/public/_panel/components/StudioNavigation.tsx#L8)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

i don't like the "store" property access. maybe introduce getEntities on schema?
</blockquote></details>

Done.
___
*[`packages/admin/src/components/Auto/AutoCell.tsx` line 24 at r1](https://reviewable.io/reviews/contember/admin/397#-N9WETvZ9ZenH0NooUeT:-N9WOroo2JalqYBYE10l:b-896fix) ([raw file](https://github.com/contember/admin/blob/7ced8bcddae1aa8aa6f5049dcf4790594728f961/packages/admin/src/components/Auto/AutoCell.tsx#L24)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

this is an utility component, should not be first in this file.
</blockquote></details>

Done.
___
*[`packages/admin/src/components/Auto/AutoCell.tsx` line 34 at r1](https://reviewable.io/reviews/contember/admin/397#-N9WCPQN6AHwHGizvu-C:-N9WPJ-75iPhbnIgRuEx:b-896fix) ([raw file](https://github.com/contember/admin/blob/7ced8bcddae1aa8aa6f5049dcf4790594728f961/packages/admin/src/components/Auto/AutoCell.tsx#L34)):*
> ```XML
> 	},
> 	props => {
> 		return <>{props.edit}{props.view}</>
> ```

Done.
___
*[`packages/admin/src/components/Auto/AutoCell.tsx` line 50 at r1](https://reviewable.io/reviews/contember/admin/397#-N9WD2Ds-ZrcnjHnZl-p:-N9WPUQC-2YxflOW2I3h:b-896fix) ([raw file](https://github.com/contember/admin/blob/7ced8bcddae1aa8aa6f5049dcf4790594728f961/packages/admin/src/components/Auto/AutoCell.tsx#L50)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

=== PRIMARY_KEY_NAME
</blockquote></details>

Done.
___
*[`packages/admin/src/components/Auto/AutoCell.tsx` line 97 at r1](https://reviewable.io/reviews/contember/admin/397#-N9WDj4DBBjHsNqqs1Gf:-N9WPkqK3zIEauZXKlXu:b-896fix) ([raw file](https://github.com/contember/admin/blob/7ced8bcddae1aa8aa6f5049dcf4790594728f961/packages/admin/src/components/Auto/AutoCell.tsx#L97)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

unify with characters in BooleanFieldView
</blockquote></details>

Done.
___
*[`packages/admin/src/components/Auto/AutoCell.tsx` line 105 at r1](https://reviewable.io/reviews/contember/admin/397#-N9WDYNmAzuNovNsI_Yp:-N9WWcE_DC0O9x3Bdasa:b-896fix) ([raw file](https://github.com/contember/admin/blob/7ced8bcddae1aa8aa6f5049dcf4790594728f961/packages/admin/src/components/Auto/AutoCell.tsx#L105)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

add getEnum method
</blockquote></details>

Done.
___
*[`packages/admin/src/components/Auto/AutoCell.tsx` line 163 at r1](https://reviewable.io/reviews/contember/admin/397#-N9WHHhZ6KZdU5x-yha7:-N9WesiX85s74t4swE2c:b-896fix) ([raw file](https://github.com/contember/admin/blob/7ced8bcddae1aa8aa6f5049dcf4790594728f961/packages/admin/src/components/Auto/AutoCell.tsx#L163)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

Json is missing
</blockquote></details>

Done.
___
*[`packages/admin/src/components/Auto/AutoCell.tsx` line 164 at r1](https://reviewable.io/reviews/contember/admin/397#-N9WCgps7_NdidNXB72c:-N9Wex1d1Ylg4uLgtqb6:b-gm86m6) ([raw file](https://github.com/contember/admin/blob/7ced8bcddae1aa8aa6f5049dcf4790594728f961/packages/admin/src/components/Auto/AutoCell.tsx#L164)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

throw an error or render some warning node.
</blockquote></details>

json is intentionally not supported
___
*[`packages/admin/src/components/Auto/AutoField.tsx` line 56 at r1](https://reviewable.io/reviews/contember/admin/397#-N9WH8IMBl75dZMv--ir:-N9WfaT-2GZbyj50UbjK:b-896fix) ([raw file](https://github.com/contember/admin/blob/7ced8bcddae1aa8aa6f5049dcf4790594728f961/packages/admin/src/components/Auto/AutoField.tsx#L56)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

Json is missing (also missing in SchemaKnownColumnType)
</blockquote></details>

Done.
___
*[`packages/admin/src/components/Auto/AutoField.tsx` line 57 at r1](https://reviewable.io/reviews/contember/admin/397#-N9WENt28sL8Kr3uGH4P:-N9Wf_X89Gh5XQfnnC_z:b-896fix) ([raw file](https://github.com/contember/admin/blob/7ced8bcddae1aa8aa6f5049dcf4790594728f961/packages/admin/src/components/Auto/AutoField.tsx#L57)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

throw error / show warning
</blockquote></details>

Done.
___
*[`packages/admin/src/components/Auto/AutoFields.tsx` line 32 at r1](https://reviewable.io/reviews/contember/admin/397#-N9WFTi57lYsyD-2Pe5M:-N9WlEKJ1m9AaiwHKqRN:b-896fix) ([raw file](https://github.com/contember/admin/blob/7ced8bcddae1aa8aa6f5049dcf4790594728f961/packages/admin/src/components/Auto/AutoFields.tsx#L32)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

static and dynamic render are same except getting the env => extract to renderAutoFields
</blockquote></details>

Done.
___
*[`packages/admin/src/components/Auto/AutoGrid.tsx` line 6 at r1](https://reviewable.io/reviews/contember/admin/397#-N9WGJjB5eLiW_YeXgNu:-N9WlRWm3bPAx8IIodK2:b-896fix) ([raw file](https://github.com/contember/admin/blob/7ced8bcddae1aa8aa6f5049dcf4790594728f961/packages/admin/src/components/Auto/AutoGrid.tsx#L6)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

move this helper function to end of file
</blockquote></details>

Done.
___
*[`packages/admin/src/components/Auto/AutoGrid.tsx` line 14 at r1](https://reviewable.io/reviews/contember/admin/397#-N9WG58z0snoQ3TLa1yy:-N9WlSZb7t-ipIHKwoDi:b-896fix) ([raw file](https://github.com/contember/admin/blob/7ced8bcddae1aa8aa6f5049dcf4790594728f961/packages/admin/src/components/Auto/AutoGrid.tsx#L14)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

you can use second argument of Array.from to map values immediatelly
</blockquote></details>

Done.
___
*[`packages/admin/src/components/Auto/AutoGrid.tsx` line 54 at r1](https://reviewable.io/reviews/contember/admin/397#-N9WFrPCA8GfjmOe7R-K:-N9WlTEZ8XKJ8wCyRKu0:b-896fix) ([raw file](https://github.com/contember/admin/blob/7ced8bcddae1aa8aa6f5049dcf4790594728f961/packages/admin/src/components/Auto/AutoGrid.tsx#L54)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

static and dynamic render are same except getting the env => extract to renderAutoGrid
</blockquote></details>

Done.
___
*[`packages/admin/src/components/Auto/AutoLabel.tsx` line 24 at r1](https://reviewable.io/reviews/contember/admin/397#-N9WGPsb7qhbPb9JPV1-:-N9WlTqN7tKY7frtQ_AU:b-896fix) ([raw file](https://github.com/contember/admin/blob/7ced8bcddae1aa8aa6f5049dcf4790594728f961/packages/admin/src/components/Auto/AutoLabel.tsx#L24)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

static and dynamic render are same except getting the env => extract to renderAutoLabel
</blockquote></details>

Done.
___
*[`packages/admin/src/components/Auto/utils.tsx` line 4 at r1](https://reviewable.io/reviews/contember/admin/397#-N9WGUdq8h1hv5vD-Hxk:-N9WlcrrCdDn4p-ta50r:b-896fix) ([raw file](https://github.com/contember/admin/blob/7ced8bcddae1aa8aa6f5049dcf4790594728f961/packages/admin/src/components/Auto/utils.tsx#L4)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

caption, description

also, imho slug > code
</blockquote></details>

Done.
___
*[`packages/admin/src/components/Auto/utils.tsx` line 10 at r1](https://reviewable.io/reviews/contember/admin/397#-N9WGpkWBlJKJE0C4aAf:-N9WlevL4UT2Ed-JU8wI:b-896fix) ([raw file](https://github.com/contember/admin/blob/7ced8bcddae1aa8aa6f5049dcf4790594728f961/packages/admin/src/components/Auto/utils.tsx#L10)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

PRIMARY_KEY_NAME
</blockquote></details>

Done.
___
*[`packages/admin/src/components/Auto/utils.tsx` line 22 at r1](https://reviewable.io/reviews/contember/admin/397#-N9WGw_HCPBEEYrlmOQ1:-N9WllugCwsr3f2PDSuy:b-896fix) ([raw file](https://github.com/contember/admin/blob/7ced8bcddae1aa8aa6f5049dcf4790594728f961/packages/admin/src/components/Auto/utils.tsx#L22)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

full value to title?
</blockquote></details>

Done.

**Review by JanTvrdik — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/admin/397)* status: 24 of 48 files reviewed, 19 unresolved discussions (waiting on @matej21)

___
*[`ee/admin-server/public/_panel/pages/studioGrid.tsx` line 31 at r1](https://reviewable.io/reviews/contember/admin/397#-N9WA_a5Dkz5NQOY4O-C:-N9WtQjG1mjmCBIwVFN3:b-896fix) ([raw file](https://github.com/contember/admin/blob/7ced8bcddae1aa8aa6f5049dcf4790594728f961/ee/admin-server/public/_panel/pages/studioGrid.tsx#L31)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

```
				{
					entityName: entity,
					filter: request.parameters.id ? {
						id: { eq: request.parameters.id },
					} : {},
				}
```

</blockquote></details>

Done.

**Review by matej21 — CHANGES_REQUESTED** [review]
> Reviewed 20 of 24 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/admin/397)* status: all files reviewed, 1 unresolved discussion (waiting on @JanTvrdik)

___
*[`build/api/binding.api.md` line 686 at r3](https://reviewable.io/reviews/contember/admin/397#-N9X2Cyk7aSUrPAWLwiB:-N9X2Cyk7aSUrPAWLwiC:b-33a3hc) ([raw file](https://github.com/contember/admin/blob/9b5577ba1a470b92a325e809dc5fe6a44fce4f65/build/api/binding.api.md#L686)):*
> ```Markdown
> 
> // @public (undocumented)
> export interface EnvAwareFunctionComponent<P> {
> ```

=> EnvironmentAwareFunctionComponent

**Review by JanTvrdik — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/admin/397)* status: 43 of 48 files reviewed, 1 unresolved discussion (waiting on @matej21)

___
*[`build/api/binding.api.md` line 686 at r3](https://reviewable.io/reviews/contember/admin/397#-N9X2Cyk7aSUrPAWLwiB:-N9aXdGc94XlxWrOx1vu:b-896fix) ([raw file](https://github.com/contember/admin/blob/9b5577ba1a470b92a325e809dc5fe6a44fce4f65/build/api/binding.api.md#L686)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

=> EnvironmentAwareFunctionComponent
</blockquote></details>

Done.

**Review by matej21 — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/admin/397)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JanTvrdik)

**Pull request merged**
