### PR TITLE
Pr/fix native input

### PR DESCRIPTION
**Pull request by matej21**
This change is [Reviewable](https://reviewable.io/reviews/contember/admin/347)

### CODE REVIEW

**Comment by VojtaStanek** [comment]
where tests?

**Review by JanTvrdik — CHANGES_REQUESTED** [review]
> Reviewed 29 of 31 files at r1, 5 of 6 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/admin/347)* status: all files reviewed, 4 unresolved discussions (waiting on @matej21)

___
*[`packages/ui/src/components/Forms/Checkbox/Checkbox.tsx` line 96 at r3](https://reviewable.io/reviews/contember/admin/347#-N5ieRmkDTS1_Wriqi5N:-N5ieRmkDTS1_Wriqi5O:be9gu39) ([raw file](https://github.com/contember/admin/blob/941f997cf4d4b9e242fe16aaa3d7906dc233d4d8/packages/ui/src/components/Forms/Checkbox/Checkbox.tsx#L96)):*
> ```XML
> 					id={outerProps.id}
> 					name={outerProps.name}
> 					placeholder={outerProps.placeholder}
> ```

how does placeholder work for checkbox?
___
*[`packages/ui/src/components/Forms/hooks/useCheckboxInput.ts` line 13 at r3](https://reviewable.io/reviews/contember/admin/347#-N5ikU9e9JImIHBqCV7N:-N5ikU9e9JImIHBqCV7O:undefined) ([raw file](https://github.com/contember/admin/blob/941f997cf4d4b9e242fe16aaa3d7906dc233d4d8/packages/ui/src/components/Forms/hooks/useCheckboxInput.ts#L13)):*
> ```XML
> 		...props,
> 		emptyValue: false,
> 		extractValue: useCallback(element => {
> ```





_Suggestion:_
```XML
		extractValue: useCallback(element => element.indeterminate ? null : element.checked, []),
```
___
*[`packages/ui/src/components/Forms/hooks/useNativeInput.ts` line 34 at r3](https://reviewable.io/reviews/contember/admin/347#-N5jAxBS4q9UzUM9OUnM:-N5jAxBS4q9UzUM9OUnN:bb7r2f0) ([raw file](https://github.com/contember/admin/blob/941f997cf4d4b9e242fe16aaa3d7906dc233d4d8/packages/ui/src/components/Forms/hooks/useNativeInput.ts#L34)):*
> ```XML
> 	min,
> 	onChange,
> 	notNull: _notNull,
> ```

why?
___
*[`packages/ui/src/components/Forms/hooks/useNativeInput.ts` line 92 at r3](https://reviewable.io/reviews/contember/admin/347#-N5jAUswD7Pv1xUBhztT:-N5jAUswD7Pv1xUBhztU:b-7j95xw) ([raw file](https://github.com/contember/admin/blob/941f997cf4d4b9e242fe16aaa3d7906dc233d4d8/packages/ui/src/components/Forms/hooks/useNativeInput.ts#L92)):*
> ```XML
> 		size,
> 
> 		// ValidationSteteProps
> ```

state

**Review by matej21 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/admin/347)* status: all files reviewed, 4 unresolved discussions (waiting on @JanTvrdik)

___
*[`packages/ui/src/components/Forms/Checkbox/Checkbox.tsx` line 96 at r3](https://reviewable.io/reviews/contember/admin/347#-N5ieRmkDTS1_Wriqi5N:-N6hStG1BDUcQspde1DO:b-wsx1dp) ([raw file](https://github.com/contember/admin/blob/941f997cf4d4b9e242fe16aaa3d7906dc233d4d8/packages/ui/src/components/Forms/Checkbox/Checkbox.tsx#L96)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

how does placeholder work for checkbox?
</blockquote></details>

required in a type, changed to undefined
___
*[`packages/ui/src/components/Forms/hooks/useCheckboxInput.ts` line 13 at r3](https://reviewable.io/reviews/contember/admin/347#-N5ikU9e9JImIHBqCV7N:-N6hSvNR4iklFgikDo7o:b-896fix) ([raw file](https://github.com/contember/admin/blob/941f997cf4d4b9e242fe16aaa3d7906dc233d4d8/packages/ui/src/components/Forms/hooks/useCheckboxInput.ts#L13)):*
> ```XML
> 		...props,
> 		emptyValue: false,
> 		extractValue: useCallback(element => {
> ```

Done.
___
*[`packages/ui/src/components/Forms/hooks/useNativeInput.ts` line 34 at r3](https://reviewable.io/reviews/contember/admin/347#-N5jAxBS4q9UzUM9OUnM:-N6hSyLC9saxqjFuY4HD:b-896fix) ([raw file](https://github.com/contember/admin/blob/941f997cf4d4b9e242fe16aaa3d7906dc233d4d8/packages/ui/src/components/Forms/hooks/useNativeInput.ts#L34)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

why?
</blockquote></details>

Done.
___
*[`packages/ui/src/components/Forms/hooks/useNativeInput.ts` line 92 at r3](https://reviewable.io/reviews/contember/admin/347#-N5jAUswD7Pv1xUBhztT:-N6hSymm3_cq2YgoA8T8:b-896fix) ([raw file](https://github.com/contember/admin/blob/941f997cf4d4b9e242fe16aaa3d7906dc233d4d8/packages/ui/src/components/Forms/hooks/useNativeInput.ts#L92)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

state
</blockquote></details>

Done.

**Review by JanTvrdik — APPROVED** [review]
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/admin/347)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matej21)

**Pull request merged**
